### ISSUE TITLE
AttributeError: 'module' object has no attribute 'normalize'

### ISSUE THREAD

**Issue by eugenio** [apierleoni/BioGraPy#6]
I tried to use the example in Draw a Blast Output tutorials but I 'm getting this error. What am I missing ?

python blast-printer.py
Traceback (most recent call last):
  File "blast-printer.py", line 49, in <module>
    name = 'Query')
  File "/usr/local/lib/python2.7/dist-packages/biograpy-1.0b0dev_r0-py2.7.egg/biograpy/tracks.py", line 153, in **init**
    self.norm = colors.normalize(vmin = self.min_score, vmax = self.max_score)
AttributeError: 'module' object has no attribute 'normalize'

**Comment by HaniceSun** [comment]
Met the same problem. It seems you need to use old version of matplotlib, e.g., 1.4.3 with BioGraPy.
Hope Andrea would like to have an updated version soon.
